CREATE TABLE `book_my_doc`.`Patient` (
	`ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
	`P_NAME` VARCHAR( 100 ) NOT NULL ,
	`P_AGE` INT( 3 ) NOT NULL ,
	`P_PASSWORD` VARCHAR( 100 ) NOT NULL
);

CREATE TABLE `book_my_doc`.`Doctor` (
	`ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
	`D_PASSWORD` VARCHAR( 100 ) NOT NULL ,
	`D_NAME` VARCHAR( 100 ) NOT NULL ,
	`D_SPECIALITY` VARCHAR( 100 ) NOT NULL ,
	`DAYS` VARCHAR( 100 ) NOT NULL ,
	`SLOT1` VARCHAR( 100 ) NOT NULL ,
	`SLOT2` VARCHAR( 100 ) NOT NULL ,
	`SLOT3` VARCHAR( 100 ) NOT NULL ,
	`SLOT4` VARCHAR( 100 ) NOT NULL
);

-- 13580 patient id
-- 987 doctor id
-- 10000 admin id

CREATE TABLE `book_my_doc`.`Appointment` (
	`ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
	`PATIENT_ID` INT NOT NULL ,
	`DOCTOR_ID` INT NOT NULL ,
	`A_DATE` DATE NOT NULL ,
	`A_SLOT` VARCHAR( 100 ) NOT NULL ,
	`A_FEEDBACK` VARCHAR( 100 ) NOT NULL ,
	`A_PRESCRIPTION` VARCHAR( 100 ) NOT NULL
);

ALTER TABLE  `Doctor` ADD  `pin` INT NOT NULL;
ALTER TABLE  `Doctor` ADD  `age` INT NOT NULL;
-- ALTER TABLE  `Doctor` CHANGE  `D_SPECIALITY`  `type` VARCHAR( 100 )  NOT NULL;

CREATE TABLE `book_my_doc`.`Admin` (
	`ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
	`A_PASSWORD` VARCHAR( 100 ) NOT NULL ,
	`A_NAME` VARCHAR( 100 ) NOT NULL
);

INSERT INTO `book_my_doc`.`Doctor` (`ID`, `D_PASSWORD`, `D_NAME`, `D_SPECIALITY`, `DAYS`, `SLOT1`, `SLOT2`, `SLOT3`, `SLOT4`, `pin`) VALUES ('10000', 'password', 'doctor1', 'dentist', 'Monday', '', '', '', '', '11000');


INSERT INTO  `book_my_doc`.`Admin` (
	`ID` ,
	`A_PASSWORD` ,
	`A_NAME`
)
VALUES (
	'10000',  'password',  '10000'
);
